//auth user
export const TEST_DISPATCH = 'TEST_DISPATcH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


//for medicines
export const GET_MEDICINES = 'GET_MEDICINES';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const REQUEST_MEDICINES = 'REQUEST_MEDICINES';


//for chemist user
export const CHEMREGISTER_SUCCESS = 'CHEMREGISTER_SUCCESS';
export const CHEMREGISTER_FAIL = 'CHEMREGISTER_SUCCESS';
export const CHEMLOGIN_SUCCESS = 'CHEMLOGIN_SUCCESS';
export const CHEMLOGIN_FAIL = 'CHEMLOGIN_FAIL';
export const CHEMUSER_LOADED = 'CHEMUSER_LOADED';
export const CHEMUSER_LOADING = 'CHEMUSER_LOADING';
export const CHEMAUTH_ERROR = 'CHEMAUTH_ERROR';
export const CHEMLOGOUT_SUCCESS = 'CHEMLOGOUT_SUCCESS';

//for medicines in return for user
export const REQUESTS_SUCCESS = 'REQUESTS_SUCCESS';
export const ACCEPT_MEDICINE = 'ACCEPT_MEDICINE';
export const REJECT_MEDICINE = 'REJECT_MEDICINE';





